### ISSUE TITLE
dtype of board is forced to float32

### ISSUE THREAD

**Issue by timorl** [david-lindner/safe-grid-gym#26]
When converting a position into an observation the dtype of the board is forced to `float32`. This breaks the assertion that the resulting observation is within the observation space for the toy envs.

**Comment by david-lindner** [comment]
Which assertion does this break exactly? Can you give me a command to reproduce this issue?

I tried to reproduce it by just checking `env.observation_space.contains(obs)` for some observations, but did not encounter any problems. See #28

**Comment by timorl** [comment]
I believe some of the changes you made fixed also this issue, thanks!
