### ISSUE TITLE
Merge with toy gridworlds

### ISSUE THREAD

**Issue by timorl** [david-lindner/safe-grid-gym#7]
To avoid code duplication perhaps we could merge this repo with the toy gridworlds one (whichever way is more convenient). This would be especially nice for having a consistent interface for corrupted gridworlds and would also make solving #6 easier.

**Comment by jvmncs** [comment]
+1 for this one

It might also be good for us to unify these repos under one GitHub user/organization?  That way when developing across them we won't be blocking each other; alternative would be to make all of us collaborators on all repos

**Comment by jvmncs** [comment]
@timorl @david-lindner I think we should prioritize this as it's getting tough to manage everything across this repo, my fork of it (which safe-grid-agents is currently pointing to), the toy environments repo, and safe-grid-agents itself.

**Comment by timorl** [comment]
So i can merge the toy repo into this one (because of the nicer name). I'm not sure how quickly I'll get around to it, so if anyone wants to do this instead feel free.

**Comment by david-lindner** [comment]
Yes I agree that merging them makes a lot of sense and it should be rather easy to just provide the additional environments. I might have some time tomorrow as well to have a look.

It also might make sense to have an organization to unify the repos. For now, I added all of you as a collaborator.
